global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:3001']

  - job_name: 'product-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['product-service:3002']

  - job_name: 'inventory-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['inventory-service:8080']
